[package]
name = "lms"
version = "0.1.0"
authors = ["Jay Kickliter <jay@kickliter.com>"]

[dependencies]
lms6002 = { path = "../lms6002" }
log = "0.4.4"
structopt = "0.2.10"
env_logger = "0.5.12"

[target.'cfg(linux)'.dependencies]
spidev = "0.3.0"
