[package]
name = "lms6002"
version = "0.1.0"
authors = ["Jay Kickliter <jay@kickliter.com>"]
readme = "README.md"

[dependencies]
bitfield = "0.13.0"
failure = "0.1.2"
failure_derive = "0.1.2"
log = "0.4.4"

[dev-dependencies]
quickcheck = "0.6"

[features]
default = ["std"]
std = []
